# Generated by Django 4.2.6 on 2023-11-30 19:49

from django.conf import settings
import django.core.validators
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name="Bandeco",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("name", models.CharField(default="", max_length=255)),
                ("horarios", models.CharField(default="", max_length=255)),
                ("contato", models.CharField(default="", max_length=255)),
                ("endereco", models.CharField(default="", max_length=255)),
                ("img_url", models.URLField(default="")),
            ],
        ),
        migrations.CreateModel(
            name="Item",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("name", models.CharField(max_length=255)),
            ],
        ),
        migrations.CreateModel(
            name="Nota",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("value", models.PositiveSmallIntegerField(default=0)),
                ("count", models.PositiveIntegerField(default=0)),
                (
                    "bandeco",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        to="ranking.bandeco",
                    ),
                ),
                (
                    "item",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE, to="ranking.item"
                    ),
                ),
            ],
        ),
        migrations.AddField(
            model_name="item",
            name="bandeco",
            field=models.ManyToManyField(through="ranking.Nota", to="ranking.bandeco"),
        ),
        migrations.CreateModel(
            name="Comentario",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("date", models.DateTimeField(auto_now_add=True)),
                ("text", models.CharField(blank=True, max_length=255)),
                (
                    "nota",
                    models.IntegerField(
                        default=0,
                        validators=[
                            django.core.validators.MinValueValidator(
                                0, "A nota não pode ser menor que 0"
                            ),
                            django.core.validators.MaxValueValidator(
                                5, "A nota não pode ser maior que 5"
                            ),
                        ],
                    ),
                ),
                (
                    "author",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
                (
                    "bandeco",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        to="ranking.bandeco",
                    ),
                ),
            ],
            options={"ordering": ["-date"],},
        ),
    ]
