# Generated by Django 3.2.12 on 2023-11-27 20:03

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('ranking', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='nota',
            name='value',
            field=models.IntegerField(default=0),
        ),
    ]
