# Generated by Django 4.2.6 on 2023-11-30 06:56

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("ranking", "0002_alter_comentario_date"),
    ]

    operations = [
        migrations.AlterField(
            model_name="comentario",
            name="text",
            field=models.CharField(blank=True, max_length=255),
        ),
    ]
