# Generated by Django 3.2.12 on 2023-11-27 20:53

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('ranking', '0003_comentario'),
    ]

    operations = [
        migrations.AddField(
            model_name='bandeco',
            name='contato',
            field=models.CharField(default='Não informado', max_length=255),
        ),
        migrations.AddField(
            model_name='bandeco',
            name='endereco',
            field=models.CharField(default='Não informado', max_length=255),
        ),
        migrations.AddField(
            model_name='bandeco',
            name='horarios',
            field=models.CharField(default='Não informado', max_length=255),
        ),
        migrations.AlterField(
            model_name='bandeco',
            name='description',
            field=models.TextField(default='Não informado', max_length=255),
        ),
        migrations.AlterField(
            model_name='bandeco',
            name='name',
            field=models.CharField(default='Não informado', max_length=255),
        ),
    ]
