# Generated by Django 3.2.12 on 2023-11-30 13:05

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('ranking', '0003_alter_comentario_text'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='comentario',
            options={'ordering': ['-date']},
        ),
    ]
