# Generated by Django 4.2.6 on 2023-11-27 21:31

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("ranking", "0004_auto_20231127_2053"),
    ]

    operations = [
        migrations.AlterField(
            model_name="nota",
            name="value",
            field=models.PositiveSmallIntegerField(default=0),
        ),
    ]
