# Generated by Django 4.2.6 on 2023-11-27 22:06

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("ranking", "0005_alter_nota_value"),
    ]

    operations = [
        migrations.AlterField(
            model_name="bandeco",
            name="contato",
            field=models.CharField(max_length=255),
        ),
        migrations.AlterField(
            model_name="bandeco",
            name="description",
            field=models.TextField(max_length=255),
        ),
        migrations.AlterField(
            model_name="bandeco",
            name="endereco",
            field=models.CharField(max_length=255),
        ),
        migrations.AlterField(
            model_name="bandeco",
            name="horarios",
            field=models.CharField(max_length=255),
        ),
        migrations.AlterField(
            model_name="bandeco", name="name", field=models.CharField(max_length=255),
        ),
    ]
