# Generated by Django 4.2.6 on 2023-11-28 00:50

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("ranking", "0007_bandeco_img_url"),
    ]

    operations = [
        migrations.AlterField(
            model_name="bandeco", name="description", field=models.TextField(),
        ),
        migrations.AlterField(
            model_name="bandeco", name="img_url", field=models.TextField(default=""),
        ),
    ]
