# Generated by Django 4.2.6 on 2023-11-28 00:51

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("ranking", "0008_alter_bandeco_description_alter_bandeco_img_url"),
    ]

    operations = [
        migrations.AlterField(
            model_name="bandeco", name="img_url", field=models.URLField(default=""),
        ),
    ]
