# Generated by Django 4.2.6 on 2023-11-28 05:10

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("ranking", "0010_remove_item_category"),
    ]

    operations = [
        migrations.RemoveField(model_name="bandeco", name="description",),
    ]
