# Generated by Django 4.2.7 on 2023-11-28 15:57

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('ranking', '0010_remove_item_category'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='bandeco',
            name='description',
        ),
        migrations.AddField(
            model_name='nota',
            name='count',
            field=models.PositiveIntegerField(default=0),
        ),
        migrations.AlterField(
            model_name='comentario',
            name='nota',
            field=models.IntegerField(default=0, validators=[django.core.validators.MinValueValidator(0, 'A nota não pode ser menor que 0'), django.core.validators.MaxValueValidator(5, 'A nota não pode ser maior que 5')]),
        ),
        migrations.RemoveField(
            model_name='bandeco',
            name='description',
        ),
    ]
